"use strict";
// Editen aquí el catálogo: los precios se expresan en centavos para evitar errores de decimales.
const FOOD_CATALOG = Object.freeze([
  {
    id: "burger-classic",
    name: "La Clásica",
    category: "Hamburguesas",
    price: 9900,
    image: "burger-classic",
    description:
      "Res a la parrilla, cheddar, vegetales frescos y nuestra salsa.",
    detail: "150 g de puro sabor",
    badge: "La favorita",
  },
  {
    id: "burger-double",
    name: "Doble Antojo",
    category: "Hamburguesas",
    price: 13900,
    image: "burger-double",
    description: "Doble carne, doble queso y todas las ganas de repetir.",
    detail: "Para un hambre en serio",
    badge: "",
  },
  {
    id: "burger-house",
    name: "La de la Casa",
    category: "Hamburguesas",
    price: 11900,
    image: "burger-house",
    description: "Carne jugosa, queso, cebolla y el toque especial de la casa.",
    detail: "Nuestra receta especial",
    badge: "",
  },
  {
    id: "pizza-pepperoni",
    name: "Pepperoni Lover",
    category: "Pizzas",
    price: 17900,
    image: "pizza-pepperoni",
    description: "Masa doradita, mozzarella y una generosa capa de pepperoni.",
    detail: "Mediana · 8 rebanadas",
    badge: "Para compartir",
  },
  {
    id: "pizza-margherita",
    name: "Margarita",
    category: "Pizzas",
    price: 15900,
    image: "pizza-margherita",
    description: "Tomate, mozzarella y albahaca. Lo simple sabe increíble.",
    detail: "Mediana · 8 rebanadas",
    badge: "",
  },
  {
    id: "pizza-special",
    name: "Especial de la Casa",
    category: "Pizzas",
    price: 19900,
    image: "pizza-special",
    description: "Nuestra selección de ingredientes sobre una base de queso.",
    detail: "Mediana · 8 rebanadas",
    badge: "",
  },
  {
    id: "combo-classic",
    name: "Combo Clásico",
    category: "Combos",
    price: 14900,
    image: "combo",
    description: "La Clásica, papas crujientes y una bebida de 355 ml.",
    detail: "Todo para una persona",
    badge: "Precio especial",
  },
  {
    id: "combo-double",
    name: "Combo Doble",
    category: "Combos",
    price: 18900,
    image: "burger-double",
    description: "Doble Antojo, papas crujientes y una bebida de 355 ml.",
    detail: "Hambre grande, combo grande",
    badge: "",
  },
  {
    id: "combo-share",
    name: "Plan para Dos",
    category: "Combos",
    price: 24900,
    image: "pizza-pepperoni",
    description: "Pizza Pepperoni mediana y dos bebidas de 355 ml.",
    detail: "El plan perfecto para compartir",
    badge: "",
  },
  {
    id: "drink-citrus",
    name: "Cítricos & Menta",
    category: "Bebidas",
    price: 3900,
    image: "drink",
    description: "Una mezcla refrescante de cítricos con un toque de menta.",
    detail: "400 ml · Sin alcohol",
    badge: "",
  },
  {
    id: "drink-fresh",
    name: "Refresco de la Casa",
    category: "Bebidas",
    price: 2900,
    image: "drink",
    description: "Bebida fría de frutas para acompañar tu pedido.",
    detail: "355 ml · Sin alcohol",
    badge: "",
  },
  {
    id: "drink-shake",
    name: "Malteada de Chocolate",
    category: "Bebidas",
    price: 5900,
    image: "shake",
    description: "Chocolate, helado y una buena dosis de felicidad.",
    detail: "400 ml · Cremosa de verdad",
    badge: "",
  },
  {
    id: "dessert-brownie",
    name: "Brownie Intenso",
    category: "Postres",
    price: 4900,
    image: "brownie",
    description: "Chocolate por dentro, una corteza irresistible por fuera.",
    detail: "Una porción de felicidad",
    badge: "",
  },
  {
    id: "dessert-icecream",
    name: "Helado a tu Ritmo",
    category: "Postres",
    price: 3900,
    image: "icecream",
    description: "Dos bolas de helado para el final más fresco.",
    detail: "2 bolas · Sabor de la casa",
    badge: "",
  },
  {
    id: "dessert-cake",
    name: "Pastel de Chocolate",
    category: "Postres",
    price: 5900,
    image: "cake",
    description: "Capas suaves de pastel con una cubierta de chocolate.",
    detail: "Rebanada individual",
    badge: "Date un gusto",
  },
]);
